kind: Service
apiVersion: v1
metadata:
  name: myapp-db-svc
  namespace: default
  labels:
    run: nebula
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  type: NodePort
  selector:
    deployment: myapp-db
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myapp-db
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: nebula
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: 'AdminP@ssw0rd'
        - name: MYSQL_DATABASE
          value: 'mysqb_db'
        - name: MYSQL_USER
          value: 'db_user'
        - name: MYSQL_PASSWORD
          value: 'db_pass'
        image: puppetseteam/pfc-myapp-db:461721
        name: myapp-db
        ports:
        - containerPort: 3306
          hostPort: 3306
          name: mysql
          protocol: TCP